services:
  - type: web
    name: livekit-voice-agent
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    dockerContext: .
    region: oregon
    buildCommand: "echo 'Build completed'"
    startCommand: "python src/main.py start"
    envVars:
      - key: LIVEKIT_URL
        value: wss://forceapp-jaadrt7a.livekit.cloud
      - key: LIVEKIT_API_KEY
        sync: false
      - key: LIVEKIT_API_SECRET
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: OUTBOUND_TRUNK_ID
        value: ST_GZ4Bo8JH4ly7
      - key: INBOUND_TRUNK_ID
        value: ST_62xofSEmFyRe
      - key: SIP_URI
        value: 6jf4gz4gbna.sip.livekit.cloud
      - key: AGENT_NAME
        value: laura-sdr
      - key: VAD_CONFIDENCE
        value: "0.8"
      - key: VAD_START_SECS
        value: "0.2"
      - key: VAD_STOP_SECS
        value: "0.8"
      - key: VAD_MIN_VOLUME
        value: "0.6"
      - key: ELEVENLABS_VOICE_ID
        value: qHkrJuifPpn95wK3rm2A
      - key: ELEVENLABS_MODEL
        value: eleven_flash_v2_5
      - key: ELEVENLABS_STABILITY
        value: "0.2"
      - key: ELEVENLABS_SIMILARITY_BOOST
        value: "0.30"
      - key: ELEVENLABS_STYLE
        value: "1.0"
      - key: ELEVENLABS_USE_SPEAKER_BOOST
        value: "false"
      - key: ELEVENLABS_OPTIMIZE_STREAMING_LATENCY
        value: "4"
      - key: OPENAI_TTS_VOICE
        value: nova
      - key: OPENAI_TTS_MODEL
        value: tts-1
      - key: OPENAI_TTS_LANGUAGE
        value: es
      - key: GROQ_STT_MODEL
        value: whisper-large-v3-turbo
      - key: GROQ_LLM_MODEL
        value: llama-3.3-70b-versatile
    scaling:
      minInstances: 1
      maxInstances: 3
